# coding: utf-8

"""
    CareDesk API

    REST API for the CareDesk platform.  All resources are served under the `/api/v1` base path. Error responses follow RFC 9457 (Problem Details for HTTP APIs) and are returned with the `application/problem+json` media type. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class PageMeta(BaseModel):
    """
    PageMeta
    """ # noqa: E501
    page: Annotated[int, Field(strict=True, ge=0)] = Field(description="Zero-based page index of the returned slice.")
    size: Annotated[int, Field(strict=True, ge=1)] = Field(description="Number of items per page.")
    total_elements: Annotated[int, Field(strict=True, ge=0)] = Field(description="Total number of items across all pages.", alias="totalElements")
    total_pages: Annotated[int, Field(strict=True, ge=0)] = Field(description="Total number of pages.", alias="totalPages")
    __properties: ClassVar[List[str]] = ["page", "size", "totalElements", "totalPages"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PageMeta from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of PageMeta from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "page": obj.get("page"),
            "size": obj.get("size"),
            "totalElements": obj.get("totalElements"),
            "totalPages": obj.get("totalPages")
        })
        return _obj


