services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infra/nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro
    restart: always
    depends_on:
      - web-client
      - ai-assistant
    networks:
      - caredesk

  web-client:
    image: ghcr.io/aet-devops26/team-k8s-commanders/web-client:${IMAGE_TAG:-latest}
    restart: always
    environment:
      PUBLIC_API_URL: ${PUBLIC_API_URL:?PUBLIC_API_URL must be set}
    networks:
      - caredesk

  ai-assistant:
    image: ghcr.io/aet-devops26/team-k8s-commanders/ai-assistant:${IMAGE_TAG:-latest}
    restart: always
    environment:
      LLM_PROVIDER: openwebui
      LLM_MODEL: openai/gpt-oss-120b
      OPENWEBUI_BASE_URL: https://gpu.aet.cit.tum.de/api
      LLM_API_KEY: ${LLM_API_KEY:?LLM_API_KEY must be set}
    networks:
      - caredesk

networks:
  caredesk:
    driver: bridge
