apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "caredesk-monitoring.fullname" . }}-tempo
  labels:
    {{- include "caredesk-monitoring.labels" . | nindent 4 }}
    app.kubernetes.io/component: tempo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.tempo.storage }}
