apiVersion: v1
kind: Service
metadata:
  name: {{ include "caredesk-monitoring.fullname" . }}-tempo
  labels:
    {{- include "caredesk-monitoring.labels" . | nindent 4 }}
    app.kubernetes.io/component: tempo
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3200
      targetPort: http
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: otlp-http
      protocol: TCP
  selector:
    {{- include "caredesk-monitoring.selectorLabels" (dict "root" . "component" "tempo") | nindent 4 }}
