{{- if .Values.monitoring.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "caredesk.fullname" . }}-prometheus
  labels:
    {{- include "caredesk.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.monitoring.storage }}
{{- end }}
