{{- if .Values.notes.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "caredesk.fullname" . }}-notes
  labels:
    {{- include "caredesk.labels" . | nindent 4 }}
    app.kubernetes.io/component: notes
spec:
  replicas: {{ .Values.notes.replicaCount }}
  strategy:
    type: {{ .Values.deploymentStrategy.type }}
  selector:
    matchLabels:
      {{- include "caredesk.selectorLabels" (dict "root" . "component" "notes") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "caredesk.selectorLabels" (dict "root" . "component" "notes") | nindent 8 }}
    spec:
      {{- include "caredesk.imagePullSecrets" . | nindent 6 }}
      containers:
        - name: notes-service
          image: {{ include "caredesk.image" (dict "root" $ "image" .Values.notes.image) | quote }}
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.notes.service.port }}
          env:
            - name: SERVER_PORT
              value: {{ .Values.notes.service.port | quote }}
            {{- include "caredesk.appVersionEnv" (dict "root" $ "image" .Values.notes.image) | nindent 12 }}
            {{- include "caredesk.dbEnv" (dict "root" $ "host" .Values.notes.dbHost "name" .Values.notes.dbName) | nindent 12 }}
          startupProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 40
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            periodSeconds: 15
            failureThreshold: 3
          resources:
            {{- toYaml .Values.notes.resources | nindent 12 }}
{{- end }}
