{{- if and .Values.images.pullSecret.create .Values.images.pullSecret.username .Values.images.pullSecret.password -}}
{{- $auth := printf "%s:%s" .Values.images.pullSecret.username .Values.images.pullSecret.password | b64enc -}}
{{- $dockerconfig := printf `{"auths":{"%s":{"username":"%s","password":"%s","email":"%s","auth":"%s"}}}` .Values.images.pullSecret.server .Values.images.pullSecret.username .Values.images.pullSecret.password .Values.images.pullSecret.email $auth -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.images.pullSecret.name }}
  labels:
    {{- include "caredesk.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $dockerconfig | b64enc | quote }}
{{- end }}
