{{- if .Values.web.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "caredesk.fullname" . }}-web
  labels:
    {{- include "caredesk.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "caredesk.selectorLabels" (dict "root" . "component" "web") | nindent 4 }}
{{- end }}
