{{- if .Values.web.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "caredesk.fullname" . }}-web
  labels:
    {{- include "caredesk.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.web.replicaCount }}
  strategy:
    type: {{ .Values.deploymentStrategy.type }}
  selector:
    matchLabels:
      {{- include "caredesk.selectorLabels" (dict "root" . "component" "web") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "caredesk.selectorLabels" (dict "root" . "component" "web") | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      {{- include "caredesk.imagePullSecrets" . | nindent 6 }}
      volumes:
        - name: nginx-conf
          configMap:
            name: {{ include "caredesk.fullname" . }}-web-nginx
            items:
              - key: default.conf
                path: default.conf
      containers:
        - name: web-client
          image: {{ include "caredesk.image" (dict "root" $ "image" .Values.web.image) | quote }}
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.web.service.port }}
          volumeMounts:
            # Override baked-in nginx config (which references `api-gateway` host
            # that only exists in Docker Compose).
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
          env:
            - name: PUBLIC_API_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "caredesk.fullname" . }}-config
                  key: PUBLIC_API_URL
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
{{- end }}
